name: Job Dependencies
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build complete"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying only if build succeeded"
