name: Multi Trigger for Dev branch
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by push or PR in DEV"
