name: Python CI
on: [push, pull_request, workflow_dispatch]
jobs:
 test:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout the Repo
      uses: actions/checkout@v5.0.0
    - name: Set up Python
      uses: actions/setup-python@v6.0.0
      with:
        python-version: "3.x"
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Test the Code
      run: pytest
